# Generated by Django 5.1.3 on 2024-12-01 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_uuid',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
