# Generated by Django 5.1.3 on 2024-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_slug_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug_uuid',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=68, null=True),
        ),
    ]
