# Generated by Django 5.1.3 on 2024-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_slug_uuid_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='article',
            name='slug_uid',
            field=models.SlugField(max_length=68, null=True),
        ),
    ]
