# Generated by Django 5.1.3 on 2024-12-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_slug_article_slug_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug_uid',
            new_name='slug',
        ),
    ]
